### ISSUE TITLE
math.clamp

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/lemur#104]
This one modifies a built-in like `math`,  which means we'll have to start shallow-copying it for each script.

**Comment by Kampfkarren** [comment]
Not exactly, you can just do what I do:

https://github.com/Kampfkarren/Roblox/blob/master/Boilerplate/string.module.lua#L22

**Comment by LPGhatguy** [comment]
You'll run into the issue that you can't enumerate over the math table as a result. That's probably pretty minor, but there's not much reason to break the case.

**Comment by Kampfkarren** [comment]
That's true, didn't think about that case.

Come to think of it, doesn't non-Roblox Lua just let you modify the default libraries directly, unlike Roblox?

**Comment by LPGhatguy** [comment]
Modifying the global `math` table is pretty unsavory since it affects stuff outside the Roblox environment you're trying to emulate. As much as possible, I'd like Lemur to keep its host environment clean, which makes me amenable for embedding in projects like LÖVE as well!
