### ISSUE TITLE
Habitat:loadFromFs silently returns nil when a file doesn't exist

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/lemur#114]
I was setting up lemur for another one of my projects, but I made a typo in the file name so it pointed to a file/directory that didn't exist. Lemur silently returned nil, and I had to read the code of Lemur to figure out it doesn't check for you.

**Comment by LPGhatguy** [comment]
The function should probably use the `ok, result` pattern like some standard library functions.

**Comment by LPGhatguy** [comment]
I don't really want to break this API _again_ switching to `ok, result` or some error object.

**Comment by LPGhatguy** [comment]
I fixed this in e42d2d5839b75abf667d60faf86ad5e3ea09624f (and a follow-up commit) by making the method throw, since it already does on some of the other I/O errors.
