### ISSUE TITLE
Support for RemoteEvents and RemoteFunctions

### ISSUE THREAD

**Issue by DeanPhillipsOKC** [LPGhatguy/lemur#159]
It would be nice if Lemur had instances for RemoteEvent and Remote function.  Additionally, it would be nice if when it is building its dependency tree it could automatically create them when *.model.json (a Rojo thing) files are encountered of those types.

Work around is simple (just add them to the dependencies to be injected by the unit test (kind of like a module script mock), but it would be great if it just worked.

**Comment by DeanPhillipsOKC** [comment]
With that said, this repos guidelines for contributions simply state to just create an issue.  Does this mean that you do not accept pull requests from non-members?

**Comment by Kampfkarren** [comment]
>  Does this mean that you do not accept pull requests from non-members?

I'm not a member, it's fine!

Although, I already made an issue for this here: #26

**Comment by DeanPhillipsOKC** [comment]
Ugh.  The name of that issue literally has RemoteEvent and RemoteFunction in it.  Not sure how I missed that.  That's what I get for staying up too late writing code, sorry folks.  Good to hear about the pull requests though!
