### ISSUE TITLE
Isn't this simulation rather than emulation?

### ISSUE THREAD

**Issue by LoganDark** [LPGhatguy/lemur#181]
`lsimr`:)

Just a joke, feel free to close the issue if you want

**Comment by Kampfkarren** [comment]
[According to this definition, it's a simulator *now* but ideally will be an emulator](https://softwareengineering.stackexchange.com/a/134783) 😉

**Comment by LoganDark** [comment]
I'm not sure how far you'll be able to go (i.e. rendering? physics?), but I'm interested in the project.
