### ISSUE TITLE
Add bit32

### ISSUE THREAD

**Issue by osyrisrblx** [LPGhatguy/lemur#208]
https://devforum.roblox.com/t/bit32-lua-library-is-now-available/320322

I'd like to add bit32 support for roblox-ts, but I need lemur to support it for unit testing.

**Comment by LPGhatguy** [comment]
We should be able to optionally depend on a LuaRocks rock that backports this API for Lua 5.1, similar to how we support high-resolution timers, JSON, and HTTP requests.
