### ISSUE TITLE
Make 'tick' use LuaSocket's socket.gettime for high performance timing

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/lemur#30]
Right now, `tick` maps to `os.clock`, which only has second resolution.

We should let tick still fall back to `os.clock` if LuaSocket is missing, but we also need to have some way to figure out if the high performance timer is enabled.

**Comment by Kampfkarren** [comment]
Wouldn't the way to figure out if the high performance timer is enabled be `pcall(require, "luasocket")`?

**Comment by Kampfkarren** [comment]
I understand the first paragraph. As for the second, what solution would return true in Roblox without adding to the client?

**Comment by LPGhatguy** [comment]
Maybe a big nasty global, like `_G.__LEMUR_NO_HIGH_PERFORMANCE_TIMER__`. It would be `nil` in Roblox and by default in Lemur, and set to `true` if Lemur failed to load LuaSocket.

Name still needs to be figured out.
