### ISSUE TITLE
Instance hierarchy

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/lemur#8]
Currently instance types do not extend off of any other class.

Ideally, this would not only help with methods like :IsA but also would make creating new instances easier.

**Comment by Kampfkarren** [comment]
Values could also be cleaned up with this (CT said they're making a superclass for them all) so they're all in one file instead of having a separate file for every single one of them (after changing Instance.new to support it).

**Comment by LPGhatguy** [comment]
It looks like this is actually implemented now!
