### ISSUE TITLE
Enums should be typeof EnumItem

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/lemur#82]
Enums right now are numbers, they should be a special type, known as `EnumItem`, which has a property that allows you to retrieve the underlying numeric value.

This is important for improving the typechecking of our values!

**Comment by Kampfkarren** [comment]
This was a part of my [PR that added every Enum automatically](https://github.com/LPGhatguy/lemur/pull/15), but it was denied.

Seems the only alternative way to do this is either really ugly wrapper code or rewriting the current "just a table" Enums.

**Comment by LPGhatguy** [comment]
I think we could make some non-ugly wrapper code that's similar to the way that instances work now. It'd probably just be a method that accepts tables like we have now, and returns the correct types.
