### ISSUE TITLE
Code Cleanup: Use busted spies instead of "callCount"

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/lemur#9]
Basically everything related to callbacks in the code uses a variable to track function calls. They litter the signal spec code.

https://github.com/LPGhatguy/lemur/blob/705238b707d48ee8ce926814aa0cf22393caa32e/lib/Signal_spec.lua

Busted provides something called "spies" for this exact usage, where it tracks if a given function is called. This would help make the code more readable.

**Comment by LPGhatguy** [comment]
Cool, I forgot that Busted did that.
