### ISSUE TITLE
Example code passes ReplicatedStorage as passedOptions for loadFromFs. This doesn't work.

### ISSUE THREAD

**Issue by Kampfkarren** [LPGhatguy/lemur#95]
This line in the README:

    local root = habitat:loadFromFs("src/roblox", ReplicatedStorage)

Doesn't actually work. You get the error:

    passedOptions must be type `table`, got type `Instance`

This isn't a PR to fix it because I'm not sure if it's *supposed* to be able to take instances, or if it's just a typo.

**Comment by LPGhatguy** [comment]
I think I just forgot to update the README with the round of breaking changes a couple months ago. In short: just pass the path, it'll return the object instead of parenting it for you like it did before.

**Comment by LPGhatguy** [comment]
Also, thanks! I didn't catch this.
